### ISSUE TITLE
Неверное указание расположения импортируемого класса ПоискНастроекКластера

### ISSUE THREAD

**Issue by yukon39** [arkuznetsov/yabr.os#2]
В конфигурационном файле `lib.config` неверно указано расположение импортируемого класса ПоискНастроекКластера.

Указано: `Классы/ПоискНастроекКластера.os`
Правильно: `src/Классы/ПоискНастроекКластера.os`

**Comment by arkuznetsov** [comment]
Спасибо! Поправил!
